appName: rag-platform-api
environment: dev

image:
  repository: ghcr.io/sbyteforge/genai-platform-local
  tag: dev-36643f8c4759eff33f71fd46403cb2e127c0dcbe
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: true
  className: nginx
  host: dev.api.local
  path: /

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  - name: AWS_ENDPOINT_URL
    value: "http://localstack.platform.svc.cluster.local:4566"
  - name: AWS_DEFAULT_REGION
    value: "us-east-1"
  - name: AWS_ACCESS_KEY_ID
    value: "test"
  - name: AWS_SECRET_ACCESS_KEY
    value: "test"
  - name: TABLE_NAME
    value: "documents-dev"
  - name: OLLAMA_URL
    value: "http://ollama.platform.svc.cluster.local:11434"
  - name: OLLAMA_MODEL
    value: "llama3.2:1b"

tableInit:
  enabled: true
